apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
resources:
  - mongo.yaml
secretGenerator:
  - name: auth
    type: Opaque
    envs:
      - auth-secrets.env
configMapGenerator:
  - name: auth
    literals:
      - AUTH_REDIRECT_URL=http://localhost/auth/callback
      - MONGODB_URI=mongodb://farmhand_user:farmhand_password@mongodb-service:27017/?authSource=farmhand&readPreference=primary&appname=settings-service&ssl=false
  - name: mongo
    literals:
      - MONGODB_USERNAME=farmhand_user
      - MONGODB_PASSWORD=farmhand_password
      - MONGODB_DATABASE=farmhand
  - name: settings
    literals:
      - MONGODB_URI=mongodb://farmhand_user:farmhand_password@mongodb-service:27017/?authSource=farmhand&readPreference=primary&appname=settings-service&ssl=false
