apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
resources:
  - mongo.yaml
secretGenerator:
  - name: auth
    type: Opaque
    envs:
      - auth-secrets.env
configMapGenerator:
  - name: auth
    literals:
      - AUTH_REDIRECT_URL=http://localhost/auth/callback
  - name: mongo
    literals:
      - MONGODB_USERNAME=farmhand_user
      - MONGODB_PASSWORD=farmhand_password
      - MONGODB_DATABASE=farmhand
