apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
secretGenerator:
  - name: auth
    type: Opaque
    env: auth-secrets.env
configMapGenerator:
  - name: properties
    literals:
      - AUTH_REDIRECT_URL=http://localhost/auth/callback
