steps:
  - name: "docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/auth",
        "-f",
        "./docker/auth.Dockerfile",
        ".",
      ]
images: ["gcr.io/$PROJECT_ID/auth"]
