version: "3.8"
services:
  auth:
    build:
      context: .
      dockerfile: ./docker/auth.Dockerfile
    image: auth:dev
    # The environment variables are read from the file ".env" in
    # the project root folder. That file should not be commited
    # to source control.
    env_file:
      - ./k8s/dev/auth.env
    environment:
      - AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
      - AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET}
      - AUTH_REDIRECT_URL=http://localhost:8080/auth/callback
    ports:
      - "8080:8080"
  settings:
    build:
      context: .
      dockerfile: ./docker/settings.Dockerfile
    image: settings:dev
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
    ports:
      - "8081:8080"
