apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: farmhand-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: farmhand
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /auth
            backend:
              serviceName: auth-service
              servicePort: 8080
